//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CoagroEnvioFacturas.APITIGO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsAPISmsCorpSoap", Namespace="http://tempuri.org/")]
    public partial class wsAPISmsCorp : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback enviarBulkSmsXMLHNOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarBulkSmsXMLNCOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarBulkSmsXMLPNOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarBulkSmsXMLGTOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarBulkSmsXMLCROperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarBulkSmsXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarBulkSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarSMSEspOperationCompleted;
        
        private System.Threading.SendOrPostCallback confirmacionSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback RespuestaSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback RespuestaBESMSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsAPISmsCorp() {
            this.Url = global::CoagroEnvioFacturas.Properties.Settings.Default.CoagroEnvioFacturas_sv_com_tigo_smscorp_wsAPISmsCorp;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event enviarBulkSmsXMLHNCompletedEventHandler enviarBulkSmsXMLHNCompleted;
        
        /// <remarks/>
        public event enviarBulkSmsXMLNCCompletedEventHandler enviarBulkSmsXMLNCCompleted;
        
        /// <remarks/>
        public event enviarBulkSmsXMLPNCompletedEventHandler enviarBulkSmsXMLPNCompleted;
        
        /// <remarks/>
        public event enviarBulkSmsXMLGTCompletedEventHandler enviarBulkSmsXMLGTCompleted;
        
        /// <remarks/>
        public event enviarBulkSmsXMLCRCompletedEventHandler enviarBulkSmsXMLCRCompleted;
        
        /// <remarks/>
        public event enviarBulkSmsXMLCompletedEventHandler enviarBulkSmsXMLCompleted;
        
        /// <remarks/>
        public event enviarBulkSmsCompletedEventHandler enviarBulkSmsCompleted;
        
        /// <remarks/>
        public event enviarSMSCompletedEventHandler enviarSMSCompleted;
        
        /// <remarks/>
        public event enviarSMSEspCompletedEventHandler enviarSMSEspCompleted;
        
        /// <remarks/>
        public event confirmacionSMSCompletedEventHandler confirmacionSMSCompleted;
        
        /// <remarks/>
        public event RespuestaSMSCompletedEventHandler RespuestaSMSCompleted;
        
        /// <remarks/>
        public event RespuestaBESMSCompletedEventHandler RespuestaBESMSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviarBulkSmsXMLHN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clRespuestaBulkSms enviarBulkSmsXMLHN(string usuario, string contrasena, string Mensajes) {
            object[] results = this.Invoke("enviarBulkSmsXMLHN", new object[] {
                        usuario,
                        contrasena,
                        Mensajes});
            return ((clRespuestaBulkSms)(results[0]));
        }
        
        /// <remarks/>
        public void enviarBulkSmsXMLHNAsync(string usuario, string contrasena, string Mensajes) {
            this.enviarBulkSmsXMLHNAsync(usuario, contrasena, Mensajes, null);
        }
        
        /// <remarks/>
        public void enviarBulkSmsXMLHNAsync(string usuario, string contrasena, string Mensajes, object userState) {
            if ((this.enviarBulkSmsXMLHNOperationCompleted == null)) {
                this.enviarBulkSmsXMLHNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarBulkSmsXMLHNOperationCompleted);
            }
            this.InvokeAsync("enviarBulkSmsXMLHN", new object[] {
                        usuario,
                        contrasena,
                        Mensajes}, this.enviarBulkSmsXMLHNOperationCompleted, userState);
        }
        
        private void OnenviarBulkSmsXMLHNOperationCompleted(object arg) {
            if ((this.enviarBulkSmsXMLHNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarBulkSmsXMLHNCompleted(this, new enviarBulkSmsXMLHNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviarBulkSmsXMLNC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clRespuestaBulkSms enviarBulkSmsXMLNC(string usuario, string contrasena, string Mensajes) {
            object[] results = this.Invoke("enviarBulkSmsXMLNC", new object[] {
                        usuario,
                        contrasena,
                        Mensajes});
            return ((clRespuestaBulkSms)(results[0]));
        }
        
        /// <remarks/>
        public void enviarBulkSmsXMLNCAsync(string usuario, string contrasena, string Mensajes) {
            this.enviarBulkSmsXMLNCAsync(usuario, contrasena, Mensajes, null);
        }
        
        /// <remarks/>
        public void enviarBulkSmsXMLNCAsync(string usuario, string contrasena, string Mensajes, object userState) {
            if ((this.enviarBulkSmsXMLNCOperationCompleted == null)) {
                this.enviarBulkSmsXMLNCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarBulkSmsXMLNCOperationCompleted);
            }
            this.InvokeAsync("enviarBulkSmsXMLNC", new object[] {
                        usuario,
                        contrasena,
                        Mensajes}, this.enviarBulkSmsXMLNCOperationCompleted, userState);
        }
        
        private void OnenviarBulkSmsXMLNCOperationCompleted(object arg) {
            if ((this.enviarBulkSmsXMLNCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarBulkSmsXMLNCCompleted(this, new enviarBulkSmsXMLNCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviarBulkSmsXMLPN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clRespuestaBulkSms enviarBulkSmsXMLPN(string usuario, string contrasena, string Mensajes) {
            object[] results = this.Invoke("enviarBulkSmsXMLPN", new object[] {
                        usuario,
                        contrasena,
                        Mensajes});
            return ((clRespuestaBulkSms)(results[0]));
        }
        
        /// <remarks/>
        public void enviarBulkSmsXMLPNAsync(string usuario, string contrasena, string Mensajes) {
            this.enviarBulkSmsXMLPNAsync(usuario, contrasena, Mensajes, null);
        }
        
        /// <remarks/>
        public void enviarBulkSmsXMLPNAsync(string usuario, string contrasena, string Mensajes, object userState) {
            if ((this.enviarBulkSmsXMLPNOperationCompleted == null)) {
                this.enviarBulkSmsXMLPNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarBulkSmsXMLPNOperationCompleted);
            }
            this.InvokeAsync("enviarBulkSmsXMLPN", new object[] {
                        usuario,
                        contrasena,
                        Mensajes}, this.enviarBulkSmsXMLPNOperationCompleted, userState);
        }
        
        private void OnenviarBulkSmsXMLPNOperationCompleted(object arg) {
            if ((this.enviarBulkSmsXMLPNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarBulkSmsXMLPNCompleted(this, new enviarBulkSmsXMLPNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviarBulkSmsXMLGT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clRespuestaBulkSms enviarBulkSmsXMLGT(string usuario, string contrasena, string Mensajes) {
            object[] results = this.Invoke("enviarBulkSmsXMLGT", new object[] {
                        usuario,
                        contrasena,
                        Mensajes});
            return ((clRespuestaBulkSms)(results[0]));
        }
        
        /// <remarks/>
        public void enviarBulkSmsXMLGTAsync(string usuario, string contrasena, string Mensajes) {
            this.enviarBulkSmsXMLGTAsync(usuario, contrasena, Mensajes, null);
        }
        
        /// <remarks/>
        public void enviarBulkSmsXMLGTAsync(string usuario, string contrasena, string Mensajes, object userState) {
            if ((this.enviarBulkSmsXMLGTOperationCompleted == null)) {
                this.enviarBulkSmsXMLGTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarBulkSmsXMLGTOperationCompleted);
            }
            this.InvokeAsync("enviarBulkSmsXMLGT", new object[] {
                        usuario,
                        contrasena,
                        Mensajes}, this.enviarBulkSmsXMLGTOperationCompleted, userState);
        }
        
        private void OnenviarBulkSmsXMLGTOperationCompleted(object arg) {
            if ((this.enviarBulkSmsXMLGTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarBulkSmsXMLGTCompleted(this, new enviarBulkSmsXMLGTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviarBulkSmsXMLCR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clRespuestaBulkSms enviarBulkSmsXMLCR(string usuario, string contrasena, string Mensajes) {
            object[] results = this.Invoke("enviarBulkSmsXMLCR", new object[] {
                        usuario,
                        contrasena,
                        Mensajes});
            return ((clRespuestaBulkSms)(results[0]));
        }
        
        /// <remarks/>
        public void enviarBulkSmsXMLCRAsync(string usuario, string contrasena, string Mensajes) {
            this.enviarBulkSmsXMLCRAsync(usuario, contrasena, Mensajes, null);
        }
        
        /// <remarks/>
        public void enviarBulkSmsXMLCRAsync(string usuario, string contrasena, string Mensajes, object userState) {
            if ((this.enviarBulkSmsXMLCROperationCompleted == null)) {
                this.enviarBulkSmsXMLCROperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarBulkSmsXMLCROperationCompleted);
            }
            this.InvokeAsync("enviarBulkSmsXMLCR", new object[] {
                        usuario,
                        contrasena,
                        Mensajes}, this.enviarBulkSmsXMLCROperationCompleted, userState);
        }
        
        private void OnenviarBulkSmsXMLCROperationCompleted(object arg) {
            if ((this.enviarBulkSmsXMLCRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarBulkSmsXMLCRCompleted(this, new enviarBulkSmsXMLCRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviarBulkSmsXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clRespuestaBulkSms enviarBulkSmsXML(string usuario, string contrasena, string Mensajes) {
            object[] results = this.Invoke("enviarBulkSmsXML", new object[] {
                        usuario,
                        contrasena,
                        Mensajes});
            return ((clRespuestaBulkSms)(results[0]));
        }
        
        /// <remarks/>
        public void enviarBulkSmsXMLAsync(string usuario, string contrasena, string Mensajes) {
            this.enviarBulkSmsXMLAsync(usuario, contrasena, Mensajes, null);
        }
        
        /// <remarks/>
        public void enviarBulkSmsXMLAsync(string usuario, string contrasena, string Mensajes, object userState) {
            if ((this.enviarBulkSmsXMLOperationCompleted == null)) {
                this.enviarBulkSmsXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarBulkSmsXMLOperationCompleted);
            }
            this.InvokeAsync("enviarBulkSmsXML", new object[] {
                        usuario,
                        contrasena,
                        Mensajes}, this.enviarBulkSmsXMLOperationCompleted, userState);
        }
        
        private void OnenviarBulkSmsXMLOperationCompleted(object arg) {
            if ((this.enviarBulkSmsXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarBulkSmsXMLCompleted(this, new enviarBulkSmsXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviarBulkSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clRespuestaBulkSms enviarBulkSms(string usuario, string contrasena, clMensajes[] Mensajes) {
            object[] results = this.Invoke("enviarBulkSms", new object[] {
                        usuario,
                        contrasena,
                        Mensajes});
            return ((clRespuestaBulkSms)(results[0]));
        }
        
        /// <remarks/>
        public void enviarBulkSmsAsync(string usuario, string contrasena, clMensajes[] Mensajes) {
            this.enviarBulkSmsAsync(usuario, contrasena, Mensajes, null);
        }
        
        /// <remarks/>
        public void enviarBulkSmsAsync(string usuario, string contrasena, clMensajes[] Mensajes, object userState) {
            if ((this.enviarBulkSmsOperationCompleted == null)) {
                this.enviarBulkSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarBulkSmsOperationCompleted);
            }
            this.InvokeAsync("enviarBulkSms", new object[] {
                        usuario,
                        contrasena,
                        Mensajes}, this.enviarBulkSmsOperationCompleted, userState);
        }
        
        private void OnenviarBulkSmsOperationCompleted(object arg) {
            if ((this.enviarBulkSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarBulkSmsCompleted(this, new enviarBulkSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviarSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clRespuesta enviarSMS(string usuario, string contrasena, string numero, string mensaje, string remitente) {
            object[] results = this.Invoke("enviarSMS", new object[] {
                        usuario,
                        contrasena,
                        numero,
                        mensaje,
                        remitente});
            return ((clRespuesta)(results[0]));
        }
        
        /// <remarks/>
        public void enviarSMSAsync(string usuario, string contrasena, string numero, string mensaje, string remitente) {
            this.enviarSMSAsync(usuario, contrasena, numero, mensaje, remitente, null);
        }
        
        /// <remarks/>
        public void enviarSMSAsync(string usuario, string contrasena, string numero, string mensaje, string remitente, object userState) {
            if ((this.enviarSMSOperationCompleted == null)) {
                this.enviarSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarSMSOperationCompleted);
            }
            this.InvokeAsync("enviarSMS", new object[] {
                        usuario,
                        contrasena,
                        numero,
                        mensaje,
                        remitente}, this.enviarSMSOperationCompleted, userState);
        }
        
        private void OnenviarSMSOperationCompleted(object arg) {
            if ((this.enviarSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarSMSCompleted(this, new enviarSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviarSMSEsp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clRespuesta enviarSMSEsp(string user, string password, string sessionid, string to, string msg) {
            object[] results = this.Invoke("enviarSMSEsp", new object[] {
                        user,
                        password,
                        sessionid,
                        to,
                        msg});
            return ((clRespuesta)(results[0]));
        }
        
        /// <remarks/>
        public void enviarSMSEspAsync(string user, string password, string sessionid, string to, string msg) {
            this.enviarSMSEspAsync(user, password, sessionid, to, msg, null);
        }
        
        /// <remarks/>
        public void enviarSMSEspAsync(string user, string password, string sessionid, string to, string msg, object userState) {
            if ((this.enviarSMSEspOperationCompleted == null)) {
                this.enviarSMSEspOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarSMSEspOperationCompleted);
            }
            this.InvokeAsync("enviarSMSEsp", new object[] {
                        user,
                        password,
                        sessionid,
                        to,
                        msg}, this.enviarSMSEspOperationCompleted, userState);
        }
        
        private void OnenviarSMSEspOperationCompleted(object arg) {
            if ((this.enviarSMSEspCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarSMSEspCompleted(this, new enviarSMSEspCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/confirmacionSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clConfirmacionSMS confirmacionSMS(string usuario, string contrasena, string Referencias) {
            object[] results = this.Invoke("confirmacionSMS", new object[] {
                        usuario,
                        contrasena,
                        Referencias});
            return ((clConfirmacionSMS)(results[0]));
        }
        
        /// <remarks/>
        public void confirmacionSMSAsync(string usuario, string contrasena, string Referencias) {
            this.confirmacionSMSAsync(usuario, contrasena, Referencias, null);
        }
        
        /// <remarks/>
        public void confirmacionSMSAsync(string usuario, string contrasena, string Referencias, object userState) {
            if ((this.confirmacionSMSOperationCompleted == null)) {
                this.confirmacionSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmacionSMSOperationCompleted);
            }
            this.InvokeAsync("confirmacionSMS", new object[] {
                        usuario,
                        contrasena,
                        Referencias}, this.confirmacionSMSOperationCompleted, userState);
        }
        
        private void OnconfirmacionSMSOperationCompleted(object arg) {
            if ((this.confirmacionSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.confirmacionSMSCompleted(this, new confirmacionSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RespuestaSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clRespuestasSMS RespuestaSMS(string usuario, string contrasena) {
            object[] results = this.Invoke("RespuestaSMS", new object[] {
                        usuario,
                        contrasena});
            return ((clRespuestasSMS)(results[0]));
        }
        
        /// <remarks/>
        public void RespuestaSMSAsync(string usuario, string contrasena) {
            this.RespuestaSMSAsync(usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void RespuestaSMSAsync(string usuario, string contrasena, object userState) {
            if ((this.RespuestaSMSOperationCompleted == null)) {
                this.RespuestaSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRespuestaSMSOperationCompleted);
            }
            this.InvokeAsync("RespuestaSMS", new object[] {
                        usuario,
                        contrasena}, this.RespuestaSMSOperationCompleted, userState);
        }
        
        private void OnRespuestaSMSOperationCompleted(object arg) {
            if ((this.RespuestaSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RespuestaSMSCompleted(this, new RespuestaSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RespuestaBESMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clRespuestasSMS RespuestaBESMS(string usuario, string contrasena, string numeroDestino) {
            object[] results = this.Invoke("RespuestaBESMS", new object[] {
                        usuario,
                        contrasena,
                        numeroDestino});
            return ((clRespuestasSMS)(results[0]));
        }
        
        /// <remarks/>
        public void RespuestaBESMSAsync(string usuario, string contrasena, string numeroDestino) {
            this.RespuestaBESMSAsync(usuario, contrasena, numeroDestino, null);
        }
        
        /// <remarks/>
        public void RespuestaBESMSAsync(string usuario, string contrasena, string numeroDestino, object userState) {
            if ((this.RespuestaBESMSOperationCompleted == null)) {
                this.RespuestaBESMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRespuestaBESMSOperationCompleted);
            }
            this.InvokeAsync("RespuestaBESMS", new object[] {
                        usuario,
                        contrasena,
                        numeroDestino}, this.RespuestaBESMSOperationCompleted, userState);
        }
        
        private void OnRespuestaBESMSOperationCompleted(object arg) {
            if ((this.RespuestaBESMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RespuestaBESMSCompleted(this, new RespuestaBESMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clRespuestaBulkSms {
        
        private int codigoEstadoField;
        
        private bool esEnvioExitosoField;
        
        private string mensajeRespuestaField;
        
        /// <remarks/>
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        public bool esEnvioExitoso {
            get {
                return this.esEnvioExitosoField;
            }
            set {
                this.esEnvioExitosoField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clListaRespuestas {
        
        private int codigoField;
        
        private string remitenteField;
        
        private string destinatarioField;
        
        private string mensajeField;
        
        private System.DateTime fechaIngresoField;
        
        /// <remarks/>
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string remitente {
            get {
                return this.remitenteField;
            }
            set {
                this.remitenteField = value;
            }
        }
        
        /// <remarks/>
        public string destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clRespuestasSMS {
        
        private int codigoEstadoField;
        
        private string mensajeRespuestaField;
        
        private clListaRespuestas[] listaField;
        
        /// <remarks/>
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public clListaRespuestas[] lista {
            get {
                return this.listaField;
            }
            set {
                this.listaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clListaEnvios {
        
        private int referenciaField;
        
        private string destinoField;
        
        private string senderIdField;
        
        private string estadoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public int referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        public string destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
            }
        }
        
        /// <remarks/>
        public string senderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clConfirmacionSMS {
        
        private int codigoEstadoField;
        
        private string mensajeRespuestaField;
        
        private clListaEnvios[] listaField;
        
        /// <remarks/>
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public clListaEnvios[] lista {
            get {
                return this.listaField;
            }
            set {
                this.listaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clRespuesta {
        
        private int codigoEstadoField;
        
        private bool esEnvioExitosoField;
        
        private string mensajeRespuestaField;
        
        private int referenciaField;
        
        /// <remarks/>
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        public bool esEnvioExitoso {
            get {
                return this.esEnvioExitosoField;
            }
            set {
                this.esEnvioExitosoField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public int referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clMensajes {
        
        private string numeroField;
        
        private string mensajeField;
        
        private string remitenteField;
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string remitente {
            get {
                return this.remitenteField;
            }
            set {
                this.remitenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void enviarBulkSmsXMLHNCompletedEventHandler(object sender, enviarBulkSmsXMLHNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarBulkSmsXMLHNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarBulkSmsXMLHNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clRespuestaBulkSms Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clRespuestaBulkSms)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void enviarBulkSmsXMLNCCompletedEventHandler(object sender, enviarBulkSmsXMLNCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarBulkSmsXMLNCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarBulkSmsXMLNCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clRespuestaBulkSms Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clRespuestaBulkSms)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void enviarBulkSmsXMLPNCompletedEventHandler(object sender, enviarBulkSmsXMLPNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarBulkSmsXMLPNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarBulkSmsXMLPNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clRespuestaBulkSms Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clRespuestaBulkSms)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void enviarBulkSmsXMLGTCompletedEventHandler(object sender, enviarBulkSmsXMLGTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarBulkSmsXMLGTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarBulkSmsXMLGTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clRespuestaBulkSms Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clRespuestaBulkSms)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void enviarBulkSmsXMLCRCompletedEventHandler(object sender, enviarBulkSmsXMLCRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarBulkSmsXMLCRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarBulkSmsXMLCRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clRespuestaBulkSms Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clRespuestaBulkSms)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void enviarBulkSmsXMLCompletedEventHandler(object sender, enviarBulkSmsXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarBulkSmsXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarBulkSmsXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clRespuestaBulkSms Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clRespuestaBulkSms)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void enviarBulkSmsCompletedEventHandler(object sender, enviarBulkSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarBulkSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarBulkSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clRespuestaBulkSms Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clRespuestaBulkSms)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void enviarSMSCompletedEventHandler(object sender, enviarSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clRespuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clRespuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void enviarSMSEspCompletedEventHandler(object sender, enviarSMSEspCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarSMSEspCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarSMSEspCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clRespuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clRespuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void confirmacionSMSCompletedEventHandler(object sender, confirmacionSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class confirmacionSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal confirmacionSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clConfirmacionSMS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clConfirmacionSMS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RespuestaSMSCompletedEventHandler(object sender, RespuestaSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RespuestaSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RespuestaSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clRespuestasSMS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clRespuestasSMS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RespuestaBESMSCompletedEventHandler(object sender, RespuestaBESMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RespuestaBESMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RespuestaBESMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clRespuestasSMS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clRespuestasSMS)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591